project:
  type: website
  output-dir: docs

website:
  title: "Demystifying ML Rostock November 5-6"
  sidebar:
    background: primary
    # logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: google.fi
        text: GitHub
    style: docked
    contents:
      - href: index.qmd
        text: Call for contributions
      - href: schedule.qmd
        text: Preliminary program
      - href: rostock.qmd
        text: Rostock
      - href: contact.qmd
        text: Contacts
style: "docked"
format:
  html:
    css: styles.css
    toc: true

execute:
  freeze: auto

